/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void txtAreaConsole_change(GTextArea source, GEvent event) { //_CODE_:txtAreaConsole:363366:
} //_CODE_:txtAreaConsole:363366:

public void btnForward_click(GImageButton source, GEvent event) { //_CODE_:btnForward:756008:
  myPort.write('w');
} //_CODE_:btnForward:756008:

public void btnLeft_click(GImageButton source, GEvent event) { //_CODE_:btnLeft:292463:
  myPort.write('a');
} //_CODE_:btnLeft:292463:

public void btnDown_click(GImageButton source, GEvent event) { //_CODE_:btnDown:409180:
  myPort.write('s');
} //_CODE_:btnDown:409180:

public void btnRight_click(GImageButton source, GEvent event) { //_CODE_:btnRight:885903:
  myPort.write('d');
} //_CODE_:btnRight:885903:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  lblHeader = new GLabel(this, 440, 20, 250, 50);
  lblHeader.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblHeader.setText("CONTROLS");
  lblHeader.setTextBold();
  lblHeader.setLocalColorScheme(GCScheme.RED_SCHEME);
  lblHeader.setOpaque(true);
  txtAreaConsole = new GTextArea(this, 20, 20, 340, 420, G4P.SCROLLBARS_VERTICAL_ONLY | G4P.SCROLLBARS_AUTOHIDE);
  txtAreaConsole.setLocalColorScheme(GCScheme.RED_SCHEME);
  txtAreaConsole.setOpaque(true);
  txtAreaConsole.addEventHandler(this, "txtAreaConsole_change");
  btnForward = new GImageButton(this, 520, 120, 100, 100, new String[] { "up-arrow.png", "up-arrow.png", "up-arrow.png" } );
  btnForward.addEventHandler(this, "btnForward_click");
  btnLeft = new GImageButton(this, 400, 230, 100, 100, new String[] { "left-arrow.png", "left-arrow.png", "left-arrow.png" } );
  btnLeft.addEventHandler(this, "btnLeft_click");
  btnDown = new GImageButton(this, 520, 340, 100, 100, new String[] { "down-arrow.png", "down-arrow.png", "down-arrow.png" } );
  btnDown.addEventHandler(this, "btnDown_click");
  btnRight = new GImageButton(this, 640, 230, 100, 100, new String[] { "right-arrow.png", "right-arrow.png", "right-arrow.png" } );
  btnRight.addEventHandler(this, "btnRight_click");
}

// Variable declarations 
// autogenerated do not edit
GLabel lblHeader; 
GTextArea txtAreaConsole; 
GImageButton btnForward; 
GImageButton btnLeft; 
GImageButton btnDown; 
GImageButton btnRight; 