/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void txtAreaConsole_change(GTextArea source, GEvent event) { //_CODE_:txtAreaConsole:363366:
} //_CODE_:txtAreaConsole:363366:

public void btnForward_click(GImageButton source, GEvent event) { //_CODE_:btnForward:756008:
  myPort.write('w');
} //_CODE_:btnForward:756008:

public void btnLeft_click(GImageButton source, GEvent event) { //_CODE_:btnLeft:292463:
  myPort.write('a');
} //_CODE_:btnLeft:292463:

public void btnDown_click(GImageButton source, GEvent event) { //_CODE_:btnDown:409180:
  myPort.write('s');
} //_CODE_:btnDown:409180:

public void btnRight_click(GImageButton source, GEvent event) { //_CODE_:btnRight:885903:
  myPort.write('d');
} //_CODE_:btnRight:885903:

public void btnStopForRoom_click(GButton source, GEvent event) { //_CODE_:btnStopForRoom:971482:
  myPort.write(32);
} //_CODE_:btnStopForRoom:971482:

public void btnCorridorChange_click(GButton source, GEvent event) { //_CODE_:btnCorridorChange:627065:
  myPort.write('c');
} //_CODE_:btnCorridorChange:627065:

public void btnRoomChange_click(GButton source, GEvent event) { //_CODE_:btnRoomChange:247543:
  myPort.write('r');
} //_CODE_:btnRoomChange:247543:

public void btnRightChange_click(GButton source, GEvent event) { //_CODE_:btnRightChange:616344:
  myPort.write('r');
} //_CODE_:btnRightChange:616344:

public void btnLeftChange_click(GButton source, GEvent event) { //_CODE_:btnLeftChange:440903:
  myPort.write('l');
} //_CODE_:btnLeftChange:440903:

public void btnStraightChange_click(GButton source, GEvent event) { //_CODE_:btnStraightChange:418568:
  myPort.write('s');
} //_CODE_:btnStraightChange:418568:

public void btnRight90_click(GImageButton source, GEvent event) { //_CODE_:btnRight90:662316:
  myPort.write('0');
} //_CODE_:btnRight90:662316:

public void btnLeft90_click(GImageButton source, GEvent event) { //_CODE_:btnLeft90:787023:
  myPort.write('9');
} //_CODE_:btnLeft90:787023:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  GButton.useRoundCorners(false);
  surface.setTitle("Sketch Window");
  lblHeader = new GLabel(this, 440, 20, 250, 50);
  lblHeader.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lblHeader.setText("CONTROLS");
  lblHeader.setTextBold();
  lblHeader.setLocalColorScheme(GCScheme.RED_SCHEME);
  lblHeader.setOpaque(true);
  txtAreaConsole = new GTextArea(this, 20, 20, 340, 420, G4P.SCROLLBARS_VERTICAL_ONLY | G4P.SCROLLBARS_AUTOHIDE);
  txtAreaConsole.setLocalColorScheme(GCScheme.RED_SCHEME);
  txtAreaConsole.setOpaque(true);
  txtAreaConsole.addEventHandler(this, "txtAreaConsole_change");
  btnForward = new GImageButton(this, 520, 120, 100, 100, new String[] { "up-arrow.png", "up-arrow.png", "up-arrow.png" } );
  btnForward.addEventHandler(this, "btnForward_click");
  btnLeft = new GImageButton(this, 400, 230, 100, 100, new String[] { "left-arrow.png", "left-arrow.png", "left-arrow.png" } );
  btnLeft.addEventHandler(this, "btnLeft_click");
  btnDown = new GImageButton(this, 520, 340, 100, 100, new String[] { "down-arrow.png", "down-arrow.png", "down-arrow.png" } );
  btnDown.addEventHandler(this, "btnDown_click");
  btnRight = new GImageButton(this, 640, 230, 100, 100, new String[] { "right-arrow.png", "right-arrow.png", "right-arrow.png" } );
  btnRight.addEventHandler(this, "btnRight_click");
  btnStopForRoom = new GButton(this, 461, 229, 200, 100);
  btnStopForRoom.setText("Stop for room");
  btnStopForRoom.setTextBold();
  btnStopForRoom.setLocalColorScheme(GCScheme.RED_SCHEME);
  btnStopForRoom.addEventHandler(this, "btnStopForRoom_click");
  btnCorridorChange = new GButton(this, 340, 460, 200, 100);
  btnCorridorChange.setText("Move into new corridor");
  btnCorridorChange.setTextBold();
  btnCorridorChange.addEventHandler(this, "btnCorridorChange_click");
  btnRoomChange = new GButton(this, 600, 460, 200, 100);
  btnRoomChange.setText("Move into new room");
  btnRoomChange.setTextBold();
  btnRoomChange.addEventHandler(this, "btnRoomChange_click");
  btnRightChange = new GButton(this, 600, 640, 200, 50);
  btnRightChange.setText("RIGHT");
  btnRightChange.setTextBold();
  btnRightChange.addEventHandler(this, "btnRightChange_click");
  btnLeftChange = new GButton(this, 340, 640, 200, 50);
  btnLeftChange.setText("LEFT");
  btnLeftChange.setTextBold();
  btnLeftChange.addEventHandler(this, "btnLeftChange_click");
  btnStraightChange = new GButton(this, 470, 580, 200, 50);
  btnStraightChange.setText("AHEAD");
  btnStraightChange.setTextBold();
  btnStraightChange.addEventHandler(this, "btnStraightChange_click");
  btnRight90 = new GImageButton(this, 650, 350, 80, 80, new String[] { "90-right.png", "90-right.png", "90-right.png" } );
  btnRight90.addEventHandler(this, "btnRight90_click");
  btnLeft90 = new GImageButton(this, 410, 350, 80, 80, new String[] { "90-left.png", "90-left.png", "90-left.png" } );
  btnLeft90.addEventHandler(this, "btnLeft90_click");
}

// Variable declarations 
// autogenerated do not edit
GLabel lblHeader; 
GTextArea txtAreaConsole; 
GImageButton btnForward; 
GImageButton btnLeft; 
GImageButton btnDown; 
GImageButton btnRight; 
GButton btnStopForRoom; 
GButton btnCorridorChange; 
GButton btnRoomChange; 
GButton btnRightChange; 
GButton btnLeftChange; 
GButton btnStraightChange; 
GImageButton btnRight90; 
GImageButton btnLeft90; 